% Automated Defacing Tools (Freesurfer software)
% It applies deface mask generated by aamod_freesurfer_deface

function [aap resp]=aamod_freesurfer_deface_apply(aap,task,subjind)
resp='';

switch task
    case 'report'
    case 'doit'

        % Get input
        wstream = aas_getstreams(aap,'out'); wstream = strrep(wstream{1},'defaced_','');
        Simg = aas_getfiles_bystream(aap,subjind,wstream); 
        [p, fn, ext] = fileparts(Simg);
        out = fullfile(p,['defaced_' fn ext]);
        
        % Apply mask
        M = spm_read_vols(spm_vol(aas_getfiles_bystream(aap,subjind,'defaced_mask')));

        inf = spm_vol(Simg);
        Y = spm_read_vols(inf);
        Y = Y.*M;
        nifti_write(out,Y,'Defaced',inf)
        
        % Now describe outputs
        aap=aas_desc_outputs(aap,subjind,['defaced_' wstream],out);
end
end



