tbx = {'-p',...
    fullfile(matlabroot,'toolbox','stats'),...
    fullfile(matlabroot,'toolbox','images'),...
    fullfile(matlabroot,'toolbox','distcomp')};
spmtoolsdir = textscan(aap.directory_conventions.spmtoolsdir,'%s','delimiter',':'); spmtoolsdir = spmtoolsdir{1};
spmtoolsdir(2:2:numel(spmtoolsdir)*2) = spmtoolsdir(:);
spmtoolsdir(1:2:numel(spmtoolsdir)) = cellstr('-a');

mcc('-m', '-C', '-v',...
    '-o',lower(spm('Ver')),...
    '-d',outdir,...
    '-N',tbx{:},...
    '-R','-singleCompThread',...
    '-a',aap.directory_conventions.spmdir,...
    spmtoolsdir{:},...
    '-a',aap.directory_conventions.eeglabdir,...
    '-a',aap.directory_conventions.GIFTdir,...
    '-a',aap.directory_conventions.BrainWaveletdir,...
    '-a',aap.directory_conventions.ANTSdir,...
    '-a',aap.directory_conventions.DCMTKdir,...
    '-a',aap.directory_conventions.templatedir,...
    'aa_standalone.m');