function zoomSubplot(handleS, zoomF)
% Zooms subplot given...
%    handleS - handle of the subplot
%    zoomF - zoom factor

posS = get(handleS, 'Position');

set(handleS, 'Position', [posS(1) - posS(3) * (zoomF-1)/2 ...
    posS(2) - posS(4) * (zoomF-1)/2 ...
    posS(3) * zoomF ...
    posS(4) * zoomF])