# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  matlab: mathworks/matlab@0

jobs:
  not_large:
    machine:
      image: 'ubuntu-2204:2022.04.1'

    environment:
      GITHUB_WORKSPACE: /home/circleci/automaticanalysis

    steps:
      - checkout
      #- matlab/install:
      #    release: R2020a
      - run:
          name: Install tools and configure aa
          command: |
            mv /home/circleci/project $GITHUB_WORKSPACE
            cd $GITHUB_WORKSPACE/.github/workflows
            python --version
            python trigger_install.py
          environment:
            LOAD_FSL: 0
            LOAD_FREESURFER: 0
            PARAMETER_XML: aap_parameters_defaults_GitHub.xml
      #- matlab/run-command:
      #    command: myscript

workflows:
  build:
    jobs:
      - not_large