# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  matlab: mathworks/matlab@0

jobs:
  not_large:
    machine:
      image: 'ubuntu-2204:2022.04.1'

    # Environment
    parameters:
      github_workspace:
        type: string
        default: ~/project
    environment:
      GITHUB_WORKSPACE: ~/project

    steps:
      - checkout
      - matlab/install:
          release: R2020a
      - run:
          name: Install tools and configure aa
          command: |
            python --version
            python trigger_install.py
          working_directory: <<parameters.github_workspace>>/.github/workflows
      - matlab/run-command:
          command: myscript

workflows:
  build:
    jobs:
      - not_large