# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  matlab: mathworks/matlab@0

jobs:
  not_large:
    machine:
      image: 'ubuntu-2204:2022.04.1'
    steps:
      - checkout
      - matlab/install:
          release: R2020a
      - run:
          name: Install tools and configure aa
          command: |
            python --version
            ls
            python trigger_install.py
          working_directory: ~/project/.github/workflows
      - matlab/run-command:
          command: myscript

workflows:
  build:
    jobs:
      - not_large