# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  matlab: mathworks/matlab@0
  python: circleci/python@2.0.3

jobs:
  not_large:
    machine:
      image: 'ubuntu-2204:2022.04.1'
    steps:
      - python/install-packages:
          version: '2.7'
          pkg-manager: pip
      - checkout
      - matlab/install
          release: 'R2020a'
      - run:
          name: Install tools and configure aa
          command: |
            python --version
            ls
            python trigger_install.py
          working_directory: 
      - matlab/run-command:
          command: myscript

workflows:
  build:
    jobs:
      - not_large