Description of aaslave_prepare
Home > aa_engine > old > aaslave_prepare.m
aaslave_prepare
PURPOSE
SYNOPSIS
function aaslave_prepare(aa_slaveid,hostname)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
aaslave_getparmpath If third parameter is present and true, don't make path
aaslave_pollsetup
aaslave_setspmvisibility
This function is called by:
SOURCE CODE
function aaslave_prepare(aa_slaveid,hostname)
global aaslave;
aaslave=[];
aaslave.aap=[];
aaslave.parmpath=aaslave_getparmpath(aaslave.aap,aa_slaveid);
aaslave.id=aa_slaveid;
aaslave_setspmvisibility
timenow=now;
aaslave.master.hostname=char(hostname);
save(fullfile(aaslave.parmpath,'iambored'),'timenow');
aaslave.lastexcitement=clock;
[s w]=unix('hostname');
myhostname=w;
save(fullfile(aaslave.parmpath,'myhostname'),'myhostname');
aaslave_pollsetup