Description of aaslave_getparmpath
Home > aa_engine > old > aaslave_getparmpath.m
aaslave_getparmpath
PURPOSE
If third parameter is present and true, don't make path
SYNOPSIS
function [pth]=aaslave_getparmpath(aap,aaslaveid,dontmakedir)
DESCRIPTION
 If third parameter is present and true, don't make path
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aas_getboredslave First check exisiting slaves to see if any are bored
aas_launchslave
aaslave_prepare
SOURCE CODE
% If third parameter is present and true, don't make path
function [pth]=aaslave_getparmpath(aap,aaslaveid,dontmakedir)
aapth=fullfile('/home',spm('GetUser'),'.aa');
pth=fullfile(aapth,sprintf('aaslave%d',aaslaveid));
makepath=1;
if (exist('dontmakedir','var'))
    if (dontmakedir)
        makepath=0;
    end;
end;
if (makepath)
    aas_makedir(aap,aapth);
    aas_makedir(aap,pth);
end;