Description of aa_closeallworkers
Home > aa_engine > aa_closeallworkers.m
aa_closeallworkers
PURPOSE
aa parallel
SYNOPSIS
function aa_closeallworkers()
DESCRIPTION
 aa parallel
 Kills all workers. They'll decay anyway, but sometimes nice to clean them
 out
CROSS-REFERENCE INFORMATION
This function calls:
aas_log Automatic analysis - log tool
aaworker_getparmpath If third parameter is present and true, don't make path
This function is called by:
aa_doprocessing_parallel Automatic analysis - do processing
SOURCE CODE
% aa parallel
% Kills all workers. They'll decay anyway, but sometimes nice to clean them
% out
%
function aa_closeallworkers()
global aaparallel
clear aap;
if (~isempty(aaparallel))
    aaprocesskey=aaparallel.processkey;
    aap.internal.parallel.processkey=aaprocesskey;
    pth=aaworker_getparmpath(aap,0,true);
    [subpth nme ext]=fileparts(pth);
    fn=dir(fullfile(subpth,['aaworker' num2str(aaprocesskey) '*']));
    for i=1:length(fn)
        if (fn(i).name(1)~='.')
            try
                fprintf('Sacking %s\n',fn(i).name);
                workerhost=load(fullfile(subpth,fn(i).name,'myhostname.mat'));
                cmd=['ssh -x ' strtrim(workerhost.myhostname) ' "ps -elf | grep ' fn(i).name ' | grep -v grep"'];
                [s rem]=unix(cmd);
                if (s)
                    aas_log(aap,false,'ssh to find process ID gave message:\n%s',w);
                end;
                while(length(rem)>0)
                    [remline rem]=strtok(rem,10);
                    for i=1:4
                        [part remline]=strtok(remline);
                    end;
                    if (length(part)>0)
                        cmd=['ssh -x ' strtrim(workerhost.myhostname) ' "kill -9 ' part '"'];
                        [s w]=unix(cmd);
                        if (s)
                            aas_log(aap,false,'Job kill gave message:\n%s',w);
                        end;
                    end;
                end;
            catch
            end;
            try
                rmdir(fullfile(subpth,fn(i).name),'s');
            catch
            end;
        end;
    end;
    aaparallel.workerlist=[];
end;