Description of aa_doprocessing_onetask
Home > aa_engine > aa_doprocessing_onetask.m
aa_doprocessing_onetask
PURPOSE
SYNOPSIS
function aa_doprocessing_onetask(aap,task,k)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
aas_getsesspath Automatic analysis - get session path
aas_getsubjpath Automatic analysis - get subject path
aas_log Automatic analysis - log tool
aas_shell function [s,w]=aas_shell(cmd)
This function is called by:
aa_doprocessing Automatic analysis - do processing
SUBFUNCTIONS
function writedoneflag(aap,fn)
function delete_doneflag(aap,stage,inpi)
SOURCE CODE
function aa_doprocessing_onetask(aap,task,k)
aap.tasklist.currenttask.epiprefix=aap.tasklist.stages{k}.epiprefix;
aap.tasklist.currenttask.extraparameters=aap.tasklist.stages{k}.extraparameters;
% retrieve description from module
[aap,description]=feval(aap.tasklist.stages{k}.name,aap,'description');
% find out whether this module needs to be executed once per study, subject or session
[aap,domain]=feval(aap.tasklist.stages{k}.name,aap,'domain');
% Now execute the module, and change the 'done' flags if task='doit'
switch (domain)
    case 'study'
        doneflag=fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{k}.name]);
        if (length(dir(doneflag)))
            if (strcmp(task,'doit'))
                aas_log(aap,0,sprintf('- completed previously: %s',description));
            end;
        else
            switch (task)
                case 'checkrequirements'
                    [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task);
                    if (length(resp)>0)
                        aas_log(aap,0,['\n***WARNING: ' resp]);
                    end;
                case 'doit'
                    tic
                    % before starting current stage, delete done_
                    % flag for next one
                    if (k<length(aap.tasklist.stages))
                        delete_doneflag(aap,k+1,-1);
                    end;
                    % now run current stage
                    aas_log(aap,0,sprintf('MODULE %s RUNNING: %s',aap.tasklist.stages{k}.name,description));
                    [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task);
                    writedoneflag(aap,doneflag);
                    aas_log(aap,0,sprintf('MODULE %s COMPLETED',aap.tasklist.stages{k}.name));
            end;
        end;
    case 'subject'
        for i=1:length(aap.acq_details.subjects)
            doneflag=fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{k}.name]);
            if (length(dir(doneflag)))
                if (strcmp(task,'doit'))
                    aas_log(aap,0,sprintf('- completed previously: %s for subject %s',description,aap.acq_details.subjects{i}));
                end;
            else
                switch (task)
                    case 'checkrequirements'
                        [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i);
                        if (length(resp)>0)
                            aas_log(aap,0,['\n***WARNING: ' resp]);
                        end;
                    case 'doit'
                        tic
                        % before starting current stage, delete done_
                        % flag for next one
                        if (k<length(aap.tasklist.stages))
                            delete_doneflag(aap,k+1,i);
                        end;
                        % now run current stage
                        aas_log(aap,0,sprintf('MODULE %s RUNNING: %s for subject %s',aap.tasklist.stages{k}.name,description,aap.acq_details.subjects{i}));
                        [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i);
                        writedoneflag(aap,doneflag);
                        aas_log(aap,0,sprintf('MODULE %s COMPLETED',aap.tasklist.stages{k}.name));
                end;
            end;
        end;
    case 'session'
        for i=1:length(aap.acq_details.subjects)
            for j=1:length(aap.acq_details.sessions)
                doneflag=fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{k}.name]);
                if (length(dir(doneflag)))
                    if (strcmp(task,'doit'))
                        aas_log(aap,0,sprintf('- completed previously: %s for subject %s session %s',description,aap.acq_details.subjects{i},aap.acq_details.sessions{j}));
                    end;
                else
                    switch (task)
                        case 'checkrequirements'
                            [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i,j);
                            if (length(resp)>0)
                                aas_log(aap,0,['\n***WARNING: ' resp]);
                            end;
                        case 'doit'
                            tic
                            % before starting current stage, delete done_
                            % flag for next one
                            if (k<length(aap.tasklist.stages))
                                delete_doneflag(aap,k+1,i);
                            end;
                            % now run current stage
                            aas_log(aap,0,sprintf('MODULE %s RUNNING: %s for subject %s session %s',aap.tasklist.stages{k}.name,description,aap.acq_details.subjects{i},aap.acq_details.sessions{j}));
                            [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i,j);
                            writedoneflag(aap,doneflag);
                            aas_log(aap,0,sprintf('MODULE %s COMPLETED',aap.tasklist.stages{k}.name));
                    end;
                end;
            end;
        end;
    otherwise
        aas_log(aap,1,sprintf('Unknown domain %s associated with stage %s',aap.tasklist.domain{k},aap.tasklist.stages{k}.name));
end;
function writedoneflag(aap,fn)
fid=fopen(fn,'w');
if (~fid)
    aas_log(aap,1,['Error writing done flag ' fn])
end;
fprintf(fid,'%f',toc);
fclose(fid);
return;
function delete_doneflag(aap,stage,inpi)
% find out whether this module needs to be executed once per study, subject
% or session
[aap,domain]=feval(aap.tasklist.stages{stage}.name,aap,'domain');
if (inpi<=0)
    boti=1;
    topi=length(aap.acq_details.subjects);
else
    boti=inpi;
    topi=inpi;
end;
switch (domain)
    case 'study'
        doneflag=fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{stage}.name]);
        if (exist(doneflag,'file'))
            cmd=['rm ' doneflag];
            [s w]=aas_shell(cmd);
            if (s~=0)
                aas_log(aap,1,w);
            end;
        end;
    case 'subject'
        for i=boti:topi
            doneflag=fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{stage}.name]);
            if (exist(doneflag,'file'))
                cmd=['rm ' doneflag];
                [s w]=aas_shell(cmd);
                if (s~=0)
                    aas_log(aap,1,w);
                end;
            end;
        end;
    case 'session'
        for i=boti:topi
            for j=1:length(aap.acq_details.sessions)
                doneflag=fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{stage}.name]);
                if (exist(doneflag,'file'))
                    cmd=['rm ' doneflag];
                    [s w]=aas_shell(cmd);
                    if (s~=0)
                        aas_log(aap,1,w);
                    end;
                end;
            end;
        end;
end;