Description of aa_doprocessing
Home > aa_engine > aa_doprocessing.m
aa_doprocessing
PURPOSE
Automatic analysis - do processing
SYNOPSIS
function [aap]=aa_doprocessing(aap)
DESCRIPTION
 Automatic analysis - do processing
 Main engine which runs different stages
 Pass parameter file set up in aa_user.m with help of recipes.
 Rhodri Cusack MRC CBU Cambridge 2004
CROSS-REFERENCE INFORMATION
This function calls:
aa_doprocessing_onetask
aas_doprocessing_initialisationmodules THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
aas_log Automatic analysis - log tool
aas_requiresversion Automatic analysis - check version
aas_shell function [s,w]=aas_shell(cmd)
This function is called by:
SOURCE CODE
% Automatic analysis - do processing
% Main engine which runs different stages
% Pass parameter file set up in aa_user.m with help of recipes.
% Rhodri Cusack MRC CBU Cambridge 2004
function [aap]=aa_doprocessing(aap)
global defaults;
aap.internal.pwd=pwd;
aas_log(aap,0,['AUTOMATIC ANALYSIS ' datestr(now)]);
aas_log(aap,0,['=============================================================']);
% Copy SPM defaults from aap structure
defaults=aap.spm.defaults;
% Check AA version
aas_requiresversion(aap);
aap=aas_doprocessing_initialisationmodules(aap);
% Now saving AAP structure
aapsavefn=fullfile(aap.acq_details.root,'aap_parameters');
if (~length(dir(aap.acq_details.root)))
    [s w]=aas_shell(['mkdir ' aap.acq_details.root]);
    if (s)
        aas_log(aap,1,sprintf('Problem making directory%s',aap.acq_details.root));
    end;
end;
aap.internal.aapversion=which('aa_doprocessing');
save(aapsavefn,'aap');
% THE MODULES IN AAP.TASKLIST.STAGES ARE RUN IF A CORRESPONDING DONE_ FLAG
% IS NOT FOUND. ONE IS CREATED AFTER SUCCESSFUL EXECUTION
% Now run stage-by-stage tasks
mytasks={'checkrequirements','doit'};
for l=1:length(mytasks)
    for k=1:length(aap.tasklist.stages)
        task=mytasks{l};
        aa_doprocessing_onetask(aap,task,k);
    end;
end;
return;