Description of aa_doprocessing_parallel
Home > aa_engine > aa_doprocessing_parallel.m
aa_doprocessing_parallel
PURPOSE
Automatic analysis - do processing
SYNOPSIS
function [aap]=aa_doprocessing_parallel(aap)
DESCRIPTION
 Automatic analysis - do processing
 Main engine which runs different stages
 Pass parameter file set up in aa_user.m with help of recipes.
 Rhodri Cusack MRC CBU Cambridge 2004
CROSS-REFERENCE INFORMATION
This function calls:
aa_closeallworkers aa parallel
aas_doprocessing_initialisationmodules THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
aas_getboredworker
aas_getsesspath Automatic analysis - get session path
aas_getsubjpath Automatic analysis - get subject path
aas_log Automatic analysis - log tool
aas_requiresversion Automatic analysis - check version
aas_shell function [s,w]=aas_shell(cmd)
aaworker_getparmpath If third parameter is present and true, don't make path
This function is called by:
SUBFUNCTIONS
function writedoneflag(aap,fn)
function delete_doneflag(aap,stage,inpi)
function [aap]=taskqueue_clear(aap)
function [aap]=taskqueue_add(aap,taskmask)
function [aap]=taskqueue_runall(aap)
function [aap]=taskqueue_runone(aap,i)
function [k0 domain0]=gettobecompletedfirst(aap,k1,i,j)
SOURCE CODE
% Automatic analysis - do processing
% Main engine which runs different stages
% Pass parameter file set up in aa_user.m with help of recipes.
% Rhodri Cusack MRC CBU Cambridge 2004
function [aap]=aa_doprocessing_parallel(aap)
global defaults;
global aaparallel
aap.internal.pwd=pwd;
if (isempty(aaparallel))
    while(1)
        aaparallel.workerlist=[];
        aaparallel.numberofworkers=8;
        aaparallel.processkey=round(rand(1)*1e6);
        aaparallel.nextworkernumber=aaparallel.processkey*1000;
        pth=aaworker_getparmpath(aap,0,true);
        [subpth nme ext]=fileparts(pth);
        fn=dir(fullfile(subpth,['aaworker' num2str(aaparallel.processkey) '*']));
        if (length(fn)==0) % No directories starting with this process key
            break;
        end;
    end;
else
    % Clear out all of the old workers: this is non-unionised enterprise
    aa_closeallworkers;
end;
aas_log(aap,0,['AUTOMATIC ANALYSIS ' datestr(now)]);
aas_log(aap,0,['=============================================================']);
aas_log(aap,0,sprintf('Parallel process ID %d',aaparallel.processkey));
% Copy SPM defaults from aap structure
defaults=aap.spm.defaults;
% Check AA version
aas_requiresversion(aap);
aap=aas_doprocessing_initialisationmodules(aap);
% Now saving AAP structure
aapsavefn=fullfile(aap.acq_details.root,'aap_parameters');
if (~length(dir(aap.acq_details.root)))
    [s w]=aas_shell(['mkdir ' aap.acq_details.root]);
    if (s)
        aas_log(aap,1,sprintf('Problem making directory%s',aap.acq_details.root));
    end;
end;
aap.internal.aapversion=which('aa_doprocessing');
save(aapsavefn,'aap');
% THE MODULES IN AAP.TASKLIST.STAGES ARE RUN IF A CORRESPONDING DONE_ FLAG
% IS NOT FOUND. ONE IS CREATED AFTER SUCCESSFUL EXECUTION
% Now run stage-by-stage tasks
aap=taskqueue_clear(aap);
mytasks={'checkrequirements','doit'};
for l=1:length(mytasks)
    for k=1:length(aap.tasklist.stages)
        task=mytasks{l};
        aap.tasklist.currenttask.epiprefix=aap.tasklist.stages{k}.epiprefix;
        aap.tasklist.currenttask.extraparameters=aap.tasklist.stages{k}.extraparameters;
        % retrieve description from module
        [aap,description]=feval(aap.tasklist.stages{k}.name,aap,'description');
        % find out whether this module needs to be executed once per study, subject or session
        [aap,domain]=feval(aap.tasklist.stages{k}.name,aap,'domain');
        % Start setting up the descriptor for the parallel queue
        clear taskmask
        taskmask.domain=domain;
        taskmask.description=description;
        taskmask.k=k;
        taskmask.task=task;
        % Now execute the module, and change the 'done' flags if task='doit'
        switch (domain)
            case 'study'
                doneflag=fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{k}.name]);
                if (length(dir(doneflag)))
                    if (strcmp(task,'doit'))
                        aas_log(aap,0,sprintf('- completed previously: %s',description));
                    end;
                else
                    switch (task)
                        case 'checkrequirements'
                            [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task);
                            if (length(resp)>0)
                                aas_log(aap,0,['\n***WARNING: ' resp]);
                            end;
                        case 'doit'
                            tic
                            % before starting current stage, delete done_
                            % flag for next one
                            if (k<length(aap.tasklist.stages))
                                delete_doneflag(aap,k+1,-1);
                            end;
                            % work out what needs to be done before we can
                            % execute this stage
                            [k0,domain0]=gettobecompletedfirst(aap,k);
                            tbcf=[];
                            switch(domain0)
                                case 'study'
                                    tbcf={fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{k0}.name])};
                                case 'subject'
                                    for i=1:length(aap.acq_details.subjects)
                                        tbcf=[tbcf {fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{k0}.name])}];
                                    end;
                                case 'session'
                                    for i=1:length(aap.acq_details.subjects)
                                        for j=1:length(aap.acq_details.sessions)
                                            tbcf=[tbcf {fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{k0}.name])}];
                                        end;
                                    end;
                            end;
                            taskmask.tobecompletedfirst=tbcf;
                            taskmask.i=0;
                            taskmask.j=0;
                            % now queue current stage
                            aas_log(aap,0,sprintf('MODULE %s QUEUED: %s',aap.tasklist.stages{k}.name,description));
                            taskmask.doneflag=doneflag;
                            aap=taskqueue_add(aap,taskmask);
                    end;
                end;
            case 'subject'
                for i=1:length(aap.acq_details.subjects)
                    doneflag=fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{k}.name]);
                    if (length(dir(doneflag)))
                        if (strcmp(task,'doit'))
                            aas_log(aap,0,sprintf('- completed previously: %s for subject %s',description,aap.acq_details.subjects{i}));
                        end;
                    else
                        switch (task)
                            case 'checkrequirements'
                                [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i);
                                if (length(resp)>0)
                                    aas_log(aap,0,['\n***WARNING: ' resp]);
                                end;
                            case 'doit'
                                tic
                                % before starting current stage, delete done_
                                % flag for next one
                                if (k<length(aap.tasklist.stages))
                                    delete_doneflag(aap,k+1,i);
                                end;
                                % work out what needs to be done before we can
                                % execute this stage
                                [k0,domain0]=gettobecompletedfirst(aap,k);
                                tbcf=[];
                                switch(domain0)
                                    case 'study'
                                        tbcf={fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{k0}.name])};
                                    case 'subject'
                                        tbcf=[tbcf {fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{k0}.name])}];
                                    case 'session'
                                        for j=1:length(aap.acq_details.sessions)
                                            tbcf=[tbcf {fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{k0}.name])}];
                                        end;
                                end;
                                taskmask.tobecompletedfirst=tbcf;
                                % now queue current stage
                                aas_log(aap,0,sprintf('MODULE %s QUEUED: %s for subject %s',aap.tasklist.stages{k}.name,description,aap.acq_details.subjects{i}));
                                taskmask.i=i;
                                taskmask.j=0;
                                taskmask.doneflag=doneflag;
                                aap=taskqueue_add(aap,taskmask);
                        end;
                    end;
                end;
            case 'session'
                for i=1:length(aap.acq_details.subjects)
                    for j=1:length(aap.acq_details.sessions)
                        doneflag=fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{k}.name]);
                        if (length(dir(doneflag)))
                            if (strcmp(task,'doit'))
                                aas_log(aap,0,sprintf('- completed previously: %s for subject %s session %s',description,aap.acq_details.subjects{i},aap.acq_details.sessions{j}));
                            end;
                        else
                            switch (task)
                                case 'checkrequirements'
                                    [aap,resp]=feval(aap.tasklist.stages{k}.name,aap,task,i,j);
                                    if (length(resp)>0)
                                        aas_log(aap,0,['\n***WARNING: ' resp]);
                                    end;
                                case 'doit'
                                    tic
                                    % before starting current stage, delete done_
                                    % flag for next one
                                    if (k<length(aap.tasklist.stages))
                                        delete_doneflag(aap,k+1,i);
                                    end;
                                    % work out what needs to be done before we can
                                    % execute this stage
                                    [k0,domain0]=gettobecompletedfirst(aap,k);
                                    tbcf=[];
                                    switch(domain0)
                                        case 'study'
                                            tbcf={fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{k0}.name])};
                                        case 'subject'
                                            tbcf=[tbcf {fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{k0}.name])}];
                                        case 'session'
                                            tbcf=[tbcf {fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{k0}.name])}];
                                    end;
                                    taskmask.tobecompletedfirst=tbcf;
                                    % now queue current stage
                                    aas_log(aap,0,sprintf('MODULE %s QUEUED: %s for subject %s session %s',aap.tasklist.stages{k}.name,description,aap.acq_details.subjects{i},aap.acq_details.sessions{j}));
                                    taskmask.i=i;
                                    taskmask.j=j;
                                    taskmask.doneflag=doneflag;
                                    aap=taskqueue_add(aap,taskmask);
                            end;
                        end;
                    end;
                end;
            otherwise
                aas_log(aap,1,sprintf('Unknown domain %s associated with stage %s',aap.tasklist.domain{k},aap.tasklist.stages{k}.name));
        end;
    end;
end;
aap=taskqueue_runall(aap);
return;
function writedoneflag(aap,fn)
fid=fopen(fn,'w');
if (~fid)
    aas_log(aap,1,['Error writing done flag ' fn])
end;
fprintf(fid,'%f',toc);
fclose(fid);
return;
function delete_doneflag(aap,stage,inpi)
% find out whether this module needs to be executed once per study, subject
% or session
[aap,domain]=feval(aap.tasklist.stages{stage}.name,aap,'domain');
if (inpi<=0)
    boti=1;
    topi=length(aap.acq_details.subjects);
else
    boti=inpi;
    topi=inpi;
end;
switch (domain)
    case 'study'
        doneflag=fullfile(aap.acq_details.root,['done_' aap.tasklist.stages{stage}.name]);
        if (exist(doneflag,'file'))
            cmd=['rm ' doneflag];
            [s w]=aas_shell(cmd);
            if (s~=0)
                aas_log(aap,1,w);
            end;
        end;
    case 'subject'
        for i=boti:topi
            doneflag=fullfile(aas_getsubjpath(aap,i),['done_' aap.tasklist.stages{stage}.name]);
            if (exist(doneflag,'file'))
                cmd=['rm ' doneflag];
                [s w]=aas_shell(cmd);
                if (s~=0)
                    aas_log(aap,1,w);
                end;
            end;
        end;
    case 'session'
        for i=boti:topi
            for j=1:length(aap.acq_details.sessions)
                doneflag=fullfile(aas_getsesspath(aap,i,j),['done_' aap.tasklist.stages{stage}.name]);
                if (exist(doneflag,'file'))
                    cmd=['rm ' doneflag];
                    [s w]=aas_shell(cmd);
                    if (s~=0)
                        aas_log(aap,1,w);
                    end;
                end;
            end;
        end;
end;
function [aap]=taskqueue_clear(aap)
aap.internal.taskqueue=[];
function [aap]=taskqueue_add(aap,taskmask)
aap.internal.taskqueue=[aap.internal.taskqueue,taskmask];
function [aap]=taskqueue_runall(aap)
njobs=length(aap.internal.taskqueue);
joblaunched=false(njobs,1);
pendingjobs=true;
while (pendingjobs)
    pendingjobs=false;
    for i=1:njobs
        if (~joblaunched(i))
            pendingjobs=true;
            readytorun=true;
            for j=1:length(aap.internal.taskqueue(i).tobecompletedfirst)
                if (~exist(aap.internal.taskqueue(i).tobecompletedfirst{j},'file'))
                    readytorun=false;
                end;
            end;
            if (readytorun)
                aap=taskqueue_runone(aap,i);
                joblaunched(i)=true;
            end;
        end;
    end;
    pause(0.5);
end;
aas_log(aap,false,'PARALLEL all jobs submitted to workers, waiting for completion');
aap=taskqueue_clear(aap);
function [aap]=taskqueue_runone(aap,i)
aas_log(aap,false,sprintf('PARALLEL waiting for free worker for job: %s',aap.internal.taskqueue(i).description));
workerid=[];
while(isempty(workerid))
    [aap, workerid]=aas_getboredworker(aap);
    if (isempty(workerid))
        pause(0.5);
    end;
end;
% Now communicate with the worker
workerpth=aaworker_getparmpath(aap,workerid);
clear task;
task.name='doprocessing';
task.aap=aap;
task.aap.tasklist.currenttask.epiprefix=aap.tasklist.stages{aap.internal.taskqueue(i).k}.epiprefix;
task.aap.tasklist.currenttask.extraparameters=aap.tasklist.stages{aap.internal.taskqueue(i).k}.extraparameters;
task.aap.internal.taskqueue=aap.internal.taskqueue(i);
save(fullfile(workerpth,'pendingtask'),'task');
aas_log(aap,false,sprintf('  ...sent to worker %d',workerid));
function [k0 domain0]=gettobecompletedfirst(aap,k1,i,j)
% first stage has no dependencies
if (k1==1)
    k0=[];
    domain0='';
    return;
end;
% previous stage, or something elsE?
tobecompletedfirst=aap.tasklist.stages{k1}.tobecompletedfirst;
if (strcmp(tobecompletedfirst,'[previous]'))
    k0=k1-1;
else
    for k0=1:(k1-1)
        if strcmp(aap.tasklist.stages{k0}.name,tobecompletedfirst)
            break;
        end;
    end;
    if (k0==k1)
        aas_log(aap,false,sprintf('stage %s is only to be executed after %s but this is not in the task list',aap.tasklist.stages(k1),tobecompleted));
    end;
end;
% now find out what domain the done flags need to cover
[aap,domain0]=feval(aap.tasklist.stages{k0}.name,aap,'domain');