Description of aas_getsubjpath
Home > aa_engine > aas_getsubjpath.m
aas_getsubjpath
PURPOSE
Automatic analysis - get subject path
SYNOPSIS
function [subjpath]=aas_getsubjpath(aap,i)
DESCRIPTION
 Automatic analysis - get subject path
 Returns path to the data directory for the subject's analyzed data
 The particular form of the subject directories is controlled by
 aap.directory_conventions.subject_directory_format
 i specifies the subject number
CROSS-REFERENCE INFORMATION
This function calls:
aas_log Automatic analysis - log tool
This function is called by:
aa_benchmark Automatic analysis - display benchmark
aa_doprocessing_onetask
aa_doprocessing_parallel Automatic analysis - do processing
aa_report Automatic analysis - produces HTML summary of analysis
aas_getimages Automatic Analysis function to retrieve image lists
aas_getsesspath Automatic analysis - get session path
SOURCE CODE
% Automatic analysis - get subject path
% Returns path to the data directory for the subject's analyzed data
% The particular form of the subject directories is controlled by
% aap.directory_conventions.subject_directory_format
%
% i specifies the subject number
function [subjpath]=aas_getsubjpath(aap,i)
switch (aap.directory_conventions.subject_directory_format)
    case 1
        numpos=findstr('_CBU',aap.acq_details.subjects{i});
        tmp=aap.acq_details.subjects{i}(numpos(1):length(aap.acq_details.subjects{i}));
        tmp=strtok(tmp,' /\\_,.');
        subjpath=fullfile(aap.acq_details.root, tmp);
    case 2
        subjpath=fullfile(aap.acq_details.root, sprintf('S%02d',i));
    case 0
        subjpath=fullfile(aap.acq_details.root, aap.directory_conventions.subject_directory_names{i});
    otherwise
        aas_log(1,sprintf('Unknown subject directory format (aap.directory_conventions.subject_directory_format=%d',aap.directory_conventions.subject_directory_format));
end;