Description of aas_getsesspath
Home > aa_engine > aas_getsesspath.m
aas_getsesspath
PURPOSE
Automatic analysis - get session path
SYNOPSIS
function [sesspath]=aas_getsesspath(aap,i,j)
DESCRIPTION
 Automatic analysis - get session path
 Returns path to the data directory for a particular session of a particular subject's analyzed data
 The particular form of the subject directories is controlled by
 aap.directory_conventions.subject_directory_format
 i specifies the subject number, j the session
CROSS-REFERENCE INFORMATION
This function calls:
aas_getsubjpath Automatic analysis - get subject path
This function is called by:
aa_benchmark Automatic analysis - display benchmark
aa_doprocessing_onetask
aa_doprocessing_parallel Automatic analysis - do processing
aa_report Automatic analysis - produces HTML summary of analysis
SOURCE CODE
% Automatic analysis - get session path
% Returns path to the data directory for a particular session of a particular subject's analyzed data
% The particular form of the subject directories is controlled by
% aap.directory_conventions.subject_directory_format
%
% i specifies the subject number, j the session
function [sesspath]=aas_getsesspath(aap,i,j)
sesspath=fullfile(aas_getsubjpath(aap,i),aap.acq_details.sessions{j});