Description of aas_makedir
Home > aa_engine > aas_makedir.m
aas_makedir
PURPOSE
aas_makedir(aap,dirname)
SYNOPSIS
function [aap,resp]=aas_makedir(aap,dirname)
DESCRIPTION
 aas_makedir(aap,dirname)
 checks a directory is made - if not makes it
 Rhodri Cusack MRC CBU Cambridge Nov 2006
CROSS-REFERENCE INFORMATION
This function calls:
aas_log Automatic analysis - log tool
aas_shell function [s,w]=aas_shell(cmd)
This function is called by:
aaworker_getparmpath If third parameter is present and true, don't make path
SOURCE CODE
% aas_makedir(aap,dirname)
% checks a directory is made - if not makes it
% Rhodri Cusack MRC CBU Cambridge Nov 2006
function [aap,resp]=aas_makedir(aap,dirname)
if (~length(dir(dirname)))
    [s w]=aas_shell(['mkdir ' dirname]);
    if (s)
        aas_log(aap,1,sprintf('Problem making directory%s',dirname));
    end;
end;