Description of aas_log
Home > aa_engine > aas_log.m
aas_log
PURPOSE
Automatic analysis - log tool
SYNOPSIS
function aas_log(aap,iserr,msg)
DESCRIPTION
 Automatic analysis - log tool
 Used to display messages
 If iserr is true, an error is generated
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aa_benchmark Automatic analysis - display benchmark
aa_closeallworkers aa parallel
aa_doprocessing Automatic analysis - do processing
aa_doprocessing_onetask
aa_doprocessing_parallel Automatic analysis - do processing
aa_report Automatic analysis - produces HTML summary of analysis
aa_requiresversion Automatic analysis - check version
aas_convertdmdx Automatic Analysis DMDX to .TXT convertor
aas_convertseries Automatic Analysis DICOM to NIFTI convertor
aas_doprocessing_initialisationmodules THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
aas_findfiles function [aap,resp]=aas_findfiles(aap,searchpath,minfiles,maxfiles)
aas_getboredworker
aas_getsubjpath Automatic analysis - get subject path
aas_launchworker
aas_makedir aas_makedir(aap,dirname)
aas_parsepvshow Automatic analysis - pvshow.pl
aas_report_addimage aa report helper function - adds an image to the HTML report
aas_requiresversion Automatic analysis - check version
aaworker_poll This is a message pump for the worker
SOURCE CODE
% Automatic analysis - log tool
% Used to display messages
% If iserr is true, an error is generated
function aas_log(aap,iserr,msg)
if (iserr)
    fprintf('\n\n**** AUTOMATIC ANALYSIS FAILED - SEE REASON AND LINE NUMBERS BELOW\n');
end;
isworker=false;
if (isfield(aap,'internal'))
    if (isfield(aap.internal,'worker'))
        isworker=true;
    end;
end;
if (isworker)
        fprintf([msg '\n']);
else
    if (aap.options.verbose>0 | iserr)
        fprintf([msg '\n']);
    end;
    if (iserr)
        cd(aap.internal.pwd)
        disp('Help pages are at http://imaging.mrc-cbu.cam.ac.uk/imaging/AutomaticAnalysisIntroduction')
        pause
        error(' ');
    end
end;