Description of aas_shell
Home > aa_engine > aas_shell.m
aas_shell
PURPOSE
function [s,w]=aas_shell(cmd)
SYNOPSIS
function [s,w]=aas_shell(cmd)
DESCRIPTION
function [s,w]=aas_shell(cmd)
 aa subroutine - wrapper for shell call
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aa_doprocessing Automatic analysis - do processing
aa_doprocessing_onetask
aa_doprocessing_parallel Automatic analysis - do processing
aas_findfiles function [aap,resp]=aas_findfiles(aap,searchpath,minfiles,maxfiles)
aas_launchworker
aas_makedir aas_makedir(aap,dirname)
aas_parsepvshow Automatic analysis - pvshow.pl
SOURCE CODE
%function [s,w]=aas_shell(cmd)
% aa subroutine - wrapper for shell call
%
function [s,w]=aas_shell(cmd)
prefix='setenv TERM dumb;'; % stops colours
[s,w]=unix([prefix cmd]);
% strip off tcsh: errors at start (see http://www.mathworks.com/support/solutions/data/1-18DNL.html?solution=1-18DNL)
[l r]=strtok(w,10);
while (length(l)>5)
    if (~strcmp(l(1:5),'tcsh:') & ~strcmp(l(1:8),'/bin/sh:'))
        break;
    end;
    [l r]=strtok(r,10);
end;
w=[l 10 r];