Description of aas_doprocessing_initialisationmodules
Home > aa_engine > aas_doprocessing_initialisationmodules.m
aas_doprocessing_initialisationmodules
PURPOSE
THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
SYNOPSIS
function [aap]=aas_doprocessing_initialisationmodules(aap)
DESCRIPTION
 THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
CROSS-REFERENCE INFORMATION
This function calls:
aas_log Automatic analysis - log tool
This function is called by:
aa_doprocessing Automatic analysis - do processing
aa_doprocessing_parallel Automatic analysis - do processing
SOURCE CODE
function [aap]=aas_doprocessing_initialisationmodules(aap)
% THE MODULES LISTED IN AAP.TASKLIST.INITIALISATIONMODULES ARE ALWAYS RUN
for k=1:length(aap.tasklist.initialisationmodules)
    % retrieve description from module
    [aap,description]=feval(aap.tasklist.initialisationmodules{k},aap,'description');
    % find out whether this module needs to be executed once per study, subject or session
    [aap,domain]=feval(aap.tasklist.initialisationmodules{k},aap,'domain');
    switch (domain)
        case 'study'
            % now run current stage
            aas_log(aap,0,sprintf('INITIALISAION MODULE %s: %s',aap.tasklist.initialisationmodules{k},description));
            [aap,resp]=feval(aap.tasklist.initialisationmodules{k},aap,'doit');
        case 'subject'
            for i=1:length(aap.acq_details.subjects)
                % now run current stage
                aas_log(aap,0,sprintf('INITIALISAION MODULE %s: %s for subject %s',aap.tasklist.initialisationmodules{k},description,aap.acq_details.subjects{i}));
                [aap,resp]=feval(aap.tasklist.initialisationmodules{k},aap,'doit',i);
            end;
        case 'session'
            for i=1:length(aap.acq_details.subjects)
                for j=1:length(aap.acq_details.sessions)
                    aas_log(aap,0,sprintf('INITIALISATION MODULE %s: %s for subject %s session %s',aap.tasklist.initialisationmodules{k},description,aap.acq_details.subjects{i},aap.acq_details.sessions{j}));
                    [aap,resp]=feval(aap.tasklist.initialisationmodules{k},aap,'doit',i,j);
                end;
            end;
        otherwise
            aas_log(aap,1,sprintf('Unknown domain %s associated with stage %s',aap.tasklist.domain{k},aap.tasklist.stages{k}));
    end;
end;