Description of aas_getboredworker
Home > aa_engine > aas_getboredworker.m
aas_getboredworker
PURPOSE
SYNOPSIS
function [aap workerid]=aas_getboredworker(aap)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
aas_launchworker
aas_log Automatic analysis - log tool
aaworker_getparmpath If third parameter is present and true, don't make path
This function is called by:
aa_doprocessing_parallel Automatic analysis - do processing
SOURCE CODE
function [aap workerid]=aas_getboredworker(aap)
global aaparallel
% First check exisiting workers to see if any are bored
workerid=[];
i=1;
while(i<=length(aaparallel.workerlist))
    pth=aaworker_getparmpath(aap,aaparallel.workerlist(i),true);
    if (exist(pth,'dir'))
        if (~exist(fullfile(pth,'pendingtask.mat'),'file') && exist(fullfile(pth,'iambored.mat'),'file'))
            workerid=aaparallel.workerlist(i);
            delete(fullfile(pth,'iambored.mat'));
            break;
        end;
    else
        aas_log(aap,0,sprintf('PARALLEL worker %d exited.',aaparallel.workerlist(i)));
        aaparallel.workerlist(i)=[];
    end;
    i=i+1;
end;
if ((length(workerid)==0) & (length(aaparallel.workerlist)<aaparallel.numberofworkers))
    while (1)
        workerid=aaparallel.nextworkernumber;
        aaparallel.nextworkernumber=aaparallel.nextworkernumber+1;
        aas_launchworker(aap,workerid);
        aaparallel.workerlist=[aaparallel.workerlist workerid];
        pth=aaworker_getparmpath(aap,workerid);
        % Every now and again, worker creation fails through network errors
        % So, only wait 60s before giving up and trying again.
        for i=1:120
            if (exist(fullfile(pth,'iambored.mat'),'file'))
                break;
            end;
            pause(1);
        end;
        if (i~=120)
            % Creating this worker has succeeded
            break;
        end;
    end;
    delete(fullfile(pth,'iambored.mat'));
end;