Description of aaworker_getparmpath
Home > aa_engine > aaworker_getparmpath.m
aaworker_getparmpath
PURPOSE
If third parameter is present and true, don't make path
SYNOPSIS
function [pth]=aaworker_getparmpath(aap,aaworkerid,dontmakedir)
DESCRIPTION
 If third parameter is present and true, don't make path
CROSS-REFERENCE INFORMATION
This function calls:
aas_makedir aas_makedir(aap,dirname)
This function is called by:
aa_closeallworkers aa parallel
aa_doprocessing_parallel Automatic analysis - do processing
aas_getboredworker
aas_launchworker
aaworker_prepare
SOURCE CODE
% If third parameter is present and true, don't make path
function [pth]=aaworker_getparmpath(aap,aaworkerid,dontmakedir)
aapth=fullfile('/home',spm('GetUser'),'.aa');
pth=fullfile(aapth,sprintf('aaworker%d',aaworkerid));
makepath=1;
if (exist('dontmakedir','var'))
    if (dontmakedir)
        makepath=0;
    end;
end;
if (makepath)
    aas_makedir(aap,aapth);
    aas_makedir(aap,pth);
end;