Description of aaworker_poll
Home > aa_engine > aaworker_poll.m
aaworker_poll
PURPOSE
This is a message pump for the worker
SYNOPSIS
function aaworker_poll(obj,event)
DESCRIPTION
 This is a message pump for the worker
CROSS-REFERENCE INFORMATION
This function calls:
aas_log Automatic analysis - log tool
aas_propagatefrom aa component used by parallel engine
aas_propagateto aa component used by parallel engine
aaworker_setspmvisibility
This function is called by:
aaworker_pollsetup
SUBFUNCTIONS
function writedoneflag(aaworker,fn)
SOURCE CODE
% This is a message pump for the worker
function aaworker_poll(obj,event)
global aaworker;
numretries=3; % For robustness, code will retry each command three times if not successful
stop(aaworker.polltimer);
mastertaskpth=fullfile(aaworker.parmpath,'pendingtask.mat');
taskpth=aas_propagatefrom(aaworker.master.hostname,mastertaskpth,'worker');
if (exist(taskpth))
    for i=1:30
        try
            task=load(taskpth);
            task=task.task;
            aaworker.aap=task.aap;
            break;
        catch
            % assume it was a file propagation delay or locking problem and so try again
            taskpth=aas_propagatefrom(aaworker.master.hostname,mastertaskpth,'worker');
            fprintf('waiting for propagation %d\n',i);
            pause(5.0);
        end;
    end;
    fprintf('AAWORKER: Found task %s here %s\n',task.name,taskpth);
    tic;
    switch (task.name)
        case 'doprocessing'
            for i=1:length(aaworker.aap.internal.taskqueue)
                % If at first you don't succeed, try, and try again
                for jj=1:numretries
                    try
                        mytask=aaworker.aap.internal.taskqueue(i);
                        switch(mytask.domain)
                            case 'study'
                                % now run current stage
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s RUNNING: %s',aaworker.aap.tasklist.stages{mytask.k}.name,mytask.description));
                                [aaworker.aap,resp]=feval(aaworker.aap.tasklist.stages{mytask.k}.name,aaworker.aap,mytask.task);
                                writedoneflag(aaworker,mytask.doneflag);
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s COMPLETED',aaworker.aap.tasklist.stages{mytask.k}.name));
                            case 'subject'
                                % now run current stage
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s RUNNING: %s for subject %s',aaworker.aap.tasklist.stages{mytask.k}.name,mytask.description,aaworker.aap.acq_details.subjects{mytask.i}));
                                [aaworker.aap,resp]=feval(aaworker.aap.tasklist.stages{mytask.k}.name,aaworker.aap,mytask.task,mytask.i);
                                writedoneflag(aaworker,mytask.doneflag);
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s COMPLETED',aaworker.aap.tasklist.stages{mytask.k}.name));
                            case 'session'
                                % now run current stage
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s RUNNING: %s for subject %s session %s',aaworker.aap.tasklist.stages{mytask.k}.name,mytask.description,aaworker.aap.acq_details.subjects{mytask.i},aaworker.aap.acq_details.sessions{mytask.j}));
                                [aaworker.aap,resp]=feval(aaworker.aap.tasklist.stages{mytask.k}.name,aaworker.aap,mytask.task,mytask.i,mytask.j);
                                writedoneflag(aaworker,mytask.doneflag);
                                aas_log(aaworker.aap,0,sprintf('AAWORKER %s COMPLETED',aaworker.aap.tasklist.stages{mytask.k}.name));
                        end;
                        jj=0;
                        break;
                    catch;
                        % make sure we're in the right directory
                        le=lasterror;
                        cd (aaworker.aap.internal.pwd);
                        aas_log(aaworker.aap,0,sprintf('AAWORKER WARNING: retrying as failed on attempt %d of %d with error:\n\t%s',jj,numretries,le.message));
                        for kk=1:length(le.stack)
                            aas_log(aaworker.aap,0,sprintf(' file %s name %s line %d',le.stack(kk).file,le.stack(kk).name,le.stack(kk).line));
                        end;
                    end;
                end;
                if (jj==3)
                        aas_log(aaworker.aap,1,sprintf('AAWORKER ERROR: %d retries did not suceed - see details above',numretries));
                end;
            end;
    end;
    try
        aaworker_setspmvisibility
        delete(taskpth);
        delete(mastertaskpth);
        timenow=now;
        boredfn=fullfile(aaworker.parmpath,'iambored.mat');
        save(boredfn,'timenow');
        aas_propagateto(aaworker.master.hostname,boredfn);
        aaworker.lastexcitement=clock;
    catch
    end;
else
    % Terminate worker if not used for 3 minutes
    if (etime(clock,aaworker.lastexcitement)>180)
        try
            aas_log(aaworker.aap,0,'There is nothing happening. I am out of here.\n');
            pth=aaworker.parmpath;
            rmdir(pth,'s');
        catch
        end;
        exit
    end;
end;
start(aaworker.polltimer);
function writedoneflag(aaworker,fn)
fid=fopen(fn,'w');
if (~fid)
    aas_log(aaworker.aap,1,['Error writing done flag ' fn])
end;
fprintf(fid,'%f',toc);
fclose(fid);
aas_propagateto(aaworker.master.hostname,fn);
return;