Description of aaworker_prepare
Home > aa_engine > aaworker_prepare.m
aaworker_prepare
PURPOSE
SYNOPSIS
function aaworker_prepare(aa_workerid,hostname)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
aas_propagateto aa component used by parallel engine
aaworker_getparmpath If third parameter is present and true, don't make path
aaworker_pollsetup
aaworker_setspmvisibility
This function is called by:
SOURCE CODE
function aaworker_prepare(aa_workerid,hostname)
global aaworker;
aaworker=[];
aaworker.aap=[];
aaworker.parmpath=aaworker_getparmpath(aaworker.aap,aa_workerid);
aaworker.id=aa_workerid;
aaworker_setspmvisibility
timenow=now;
aaworker.master.hostname=char(hostname);
fn=fullfile(aaworker.parmpath,'iambored.mat');
save(fn,'timenow');
aas_propagateto(aaworker.master.hostname,fn);
aas_propagateto(aaworker.master.hostname,fn);
aaworker.lastexcitement=clock;
[s w]=unix('hostname');
myhostname=w;
fn=fullfile(aaworker.parmpath,'myhostname.mat');
save(fn,'myhostname');
aas_propagateto(aaworker.master.hostname,fn);
aaworker_pollsetup